### ISSUE TITLE
Support patternProperties

### ISSUE THREAD

**Issue by chrisdostert** [opspec-io/schema-visualizer#5]
Background:
opspec 0.1.3 uses json schema patternProperties; opspec 0.1.2 didn't.
As it turns out, the schema visualizer doesn't support visualizing patternProperties.
This is a bad user experience as they then can't visualize the entire spec. 

[link to opspec 0.1.2 visualizer](https://opspec.io/schema-visualizer/?schema=https://spec.opspec.io/0.1.2/schema/manifest.json)

[link to opspec 0.1.3 visualizer](https://opspec.io/schema-visualizer/?schema=https://opspec.io/spec/0.1.3/schema/packageManifest.json)

User Story:
As a consumer of opspec 0.1.3
I would like schema-visualizer to display patternProperties ([example](https://github.com/opspec-io/spec/blob/master/latest/schema/scg.json#L33)) like properties ([example](https://github.com/opspec-io/spec/blob/master/latest/schema/scg.json#L23))
In order to visualize the entire spec

**Comment by chrisdostert** [comment]
@SudhindraKovalam have any interest in taking this on?

**Comment by SudhindraKovalam** [comment]
Sure..
I'd like to take a stab at it..

Sent from my Phone

On Mar 4, 2017, at 10:35 AM, Chris Dostert <notifications@github.com<mailto:notifications@github.com>> wrote:


@SudhindraKovalam<https://github.com/SudhindraKovalam> have any interest in taking this on?
